// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://luvlzamdgwjtcaqekgcj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1dmx6YW1kZ3dqdGNhcWVrZ2NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MDI4ODAsImV4cCI6MjA3NTQ3ODg4MH0.o52vsbJxH9e-3Tf_bNXO3vw7B_C3qpJV3unA5xXOJgU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);